repos:
- repo: https://github.com/psf/black
  rev: 21.5b1
  hooks:
    - id: black
      language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace  # This hook trims trailing whitespace.
    - id: check-docstring-first  # Checks a common error of defining a docstring after code.
    - id: check-merge-conflict  # Check for files that contain merge conflict strings.
    - id: check-yaml  # This hook checks yaml files for parseable syntax.
    - id: detect-private-key  # Detects the presence of private keys.
    - id: check-symlinks
    - id: check-toml
    - id: end-of-file-fixer
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.8.0
  hooks:
    - id: python-no-eval  # A quick check for the eval() built-in function.
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      # additional_dependencies: [flake8-docstrings, flake8-bugbear, flake8-spellcheck, flake8-import-order]
