name: Run C tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.pre-commit-config.yaml'
      - '**.md'

jobs:
  c-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile C tests
      run: |
        cd ./tests/c/
        make test
    - name: Run C tests
      run: |
        cd ./tests/c/
        ./test
    - name: Clean
      run: |
        make clean
